// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// runGeneticAlgorithm
IntegerMatrix runGeneticAlgorithm(const int POPSIZE, const int NPERS, const int MAXGENS, const double PXOVER, const double PMUTATION, const double critval, const double alpha, const int NITEM, const int ITER, const NumericMatrix& VAR, const NumericMatrix& MAXVAR, const NumericMatrix& SijMatrix);
RcppExport SEXP _mokken_runGeneticAlgorithm(SEXP POPSIZESEXP, SEXP NPERSSEXP, SEXP MAXGENSSEXP, SEXP PXOVERSEXP, SEXP PMUTATIONSEXP, SEXP critvalSEXP, SEXP alphaSEXP, SEXP NITEMSEXP, SEXP ITERSEXP, SEXP VARSEXP, SEXP MAXVARSEXP, SEXP SijMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type POPSIZE(POPSIZESEXP);
    Rcpp::traits::input_parameter< const int >::type NPERS(NPERSSEXP);
    Rcpp::traits::input_parameter< const int >::type MAXGENS(MAXGENSSEXP);
    Rcpp::traits::input_parameter< const double >::type PXOVER(PXOVERSEXP);
    Rcpp::traits::input_parameter< const double >::type PMUTATION(PMUTATIONSEXP);
    Rcpp::traits::input_parameter< const double >::type critval(critvalSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const int >::type NITEM(NITEMSEXP);
    Rcpp::traits::input_parameter< const int >::type ITER(ITERSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type VAR(VARSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type MAXVAR(MAXVARSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type SijMatrix(SijMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(runGeneticAlgorithm(POPSIZE, NPERS, MAXGENS, PXOVER, PMUTATION, critval, alpha, NITEM, ITER, VAR, MAXVAR, SijMatrix));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mokken_runGeneticAlgorithm", (DL_FUNC) &_mokken_runGeneticAlgorithm, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_mokken(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
