# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runGeneticAlgorithm <- function(POPSIZE, NPERS, MAXGENS, PXOVER, PMUTATION, critval, alpha, NITEM, ITER, VAR, MAXVAR, SijMatrix) {
    .Call(`_mokken_runGeneticAlgorithm`, POPSIZE, NPERS, MAXGENS, PXOVER, PMUTATION, critval, alpha, NITEM, ITER, VAR, MAXVAR, SijMatrix)
}

